# -*- coding: utf-8 -*-
# Generated by Django 1.11b1 on 2017-04-06 11:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tests', '0003_gallery_galleryimage'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='locations',
            field=models.ManyToManyField(blank=True, related_name='articles_set_here', to='tests.Place'),
        ),
    ]
